@isTest
public with sharing class TestDataFactory {
    
    /*

    public static List<Dispute__c> createDisputes(Integer number) {
        List<Dispute__c> disputes = new List<Dispute__c>();
        
        for(Integer i = 0; i < number; i++) {
           
            Dispute__c dispute = new Dispute__c();
           dispute.Dispute_Name__c = 'Test-Name ' + i;
           dispute.Dispute_ID__c = 1123 + i;
           //Judge is required???
           //Court-date-time field required!!!!
           disputes.add(dispute);

        }

        return disputes;
    }


    public static List<Judge__c> createJudges(Integer number) {
        List<Judge__c> judges = new List<Judge__c>();
        
        for(Integer i = 0; i < number; i++) {
           
           Judge__c judge = new Judge__c();
           judge.Name = 'Test-Name ' + i;
           judges.add(judge);

        }

        return judges;
    }

    public static List<Petitioner__c> createPetitioner(Integer number) {
        List<Petitioner__c> petitioners = new List<Petitioner__c>();
        
        for(Integer i = 0; i < number; i++) {
           Petitioner__c petitioner = new Petitioner__c();
           petitioner.Name = 'Test-Name ' + i;
           petitioner.Dispute__c = 1123 + i;
           petitioner.Email = 'email';
           petitioners.add(petitioner);

        }

        return petitioners;
    }

    public static List<Responder__c> createResponder(Integer number) {
         List<Responder__c> responders = new List<Responder__c>();
        
        for(Integer i = 0; i < number; i++) {
           Responder__c responder = new Responder__c();
           responder.Name = 'Test-Name ' + i;
           responder.Dispute__c = 1123 + i;
           responder.Email = 'email';
           responders.add(responder);

        }

        return responders;
    }

    */
    
}
